### ISSUE TITLE
SintaxError

### ISSUE THREAD

**Issue by aralom** [amjadsibili/reCAPTCHA-bypass#3]
Hello, @amjadsibili when i run show this error.
How to be fixed?

Regards!

![error](https://user-images.githubusercontent.com/6155938/49392776-0e2c3a00-f6f5-11e8-8dcb-c32adfea442a.png)

**Comment by amjadsibili** [comment]
Yeah, that's just a compatibility issue. The code was written in python 2 and your interpreter is python3. I just committed the code into python3 supportable.
